[global]
log-level = 'warn'

[repository]
repository = "opendal:sftp"

[repository.options]
user = "pascalwhoop"
endpoint = "192.168.1.99"
root = "/mnt/vault/Backup/restic"

[forget]
keep-daily = 7
keep-weekly = 4
keep-yearly = 3

[backup]
iglob-files = ["/Users/pascal/.config/rustic/ignore.iglob"]
one-file-system = true

[[backup.snapshots]]
name = "home"
sources = ["/Users/"]
git-ignore = true

# "OLD" crestic config file
# # =============================
# # Global Configuration
# # =============================
# [global]
# 
# [global.environ]
# # Global environment variables
# GOOGLE_APPLICATION_CREDENTIALS: ~/.config/restic/gcs-credentials.json
# 
# # =============================
# # Local Backup to Vault
# # =============================
# [local]
# repo: /mnt/vault/Backup/restic
# password-file: ~/.config/restic/local.passw
# 
# [local.backup]
# _arguments: /
# one-file-system
# exclude-file: ~/.config/restic/excludes.root.txt
#     ~/.config/restic/excludes.core.txt
# verbose
# 
# [local.forget]
# keep-daily: 7
# keep-weekly: 4
# keep-monthly: 6
# keep-yearly: 3
# prune
# keep-within: 1y
# 
# # =============================
# # Offsite Backup to Google Cloud Storage
# # =============================
# [@offsite]
# repo: gs:curiloo-home-backup:/restic
# password-file: ~/.config/restic/offsite.passw
# 
# [@offsite.environ]
# # Environment variables for GCS authentication
# GOOGLE_APPLICATION_CREDENTIALS: ~/.config/restic/gcs-credentials.json
# 
# [root@offsite.backup]
# _arguments: /
# one-file-system
# exclude-file: ~/.config/restic/excludes.root.txt
#     ~/.config/restic/excludes.core.txt
# verbose
# 
# [vault@offsite.backup]
# _arguments: /mnt/vault/
# one-file-system
# exclude-file: ~/.config/restic/excludes.vault.txt
#     ~/.config/restic/excludes.core.txt
# verbose
# 
# [@offsite.forget]
# keep-yearly: 5
# prune
# max-unused: unlimited
# keep-within: 1y
# repack-cacheable-only
# 
# # =============================
# # Utility Commands
# # =============================
# # todo
